stages:
  prepare:
    cmd: ./convert_imgs.sh && python3 prepare.py
    deps:
      - data/raw
    outs:
      - data/train
      - data/test

  train:
    cmd: python3 train.py
    deps:
      - data/train
      - data/test
    outs:
      - data/models

  test:
    cmd: python3 test.py
    deps:
      - data/models
    metrics:
      - data/metrics.json
