name: simple_regularized_cnn

load:
  img_size: 256
  batch_size: 32
  validation_split: 0.8
  augmentations:
    brightness_range:
      - 0.75
      - 1.05
    zoom_range:
      - 0.85
      - 1.00
    shear_range: 0.05

train:
  lr: 0.0001
  epochs: 100

  callbacks:
    tensorboard: true
    modelcheckpoint: true
    earlystopping: true
    stopping_delta: 0.001
    stopping_patience: 5

test:
  threshold: 0.5

visualize:
  img_path: 'data/train/true/IMG_6608.jpg'
  filter_layer_visualizer:
    layer_name: 'conv2d_2'
