name: simple_regularized_cnn

load:
  img_size: 256
  batch_size: 8
  validation_split: 0.7
  augmentations:
    # This is a dummy augmentation, does nothing
    zoom_range: 0.0

train:
  lr: 0.0005
  epochs: 20

  callbacks:
    tensorboard: false
    modelcheckpoint: true
    earlystopping: true
    stopping_delta: 0.001
    stopping_patience: 5

test:
  threshold: 0.5
